const fs = require('fs');
let content = fs.readFileSync('js/supabaseClient.js', 'utf8');
const lines = content.split('\n');

// Lines before the corrupt block (index 0-751 = original lines 1-752)
const before = lines.slice(0, 752).join('\n');

// Lines after the corrupt block (index 755 onwards = original line 756+)
const after = lines.slice(755).join('\n');

// Proper Stage 8 replacement with real newlines
const stage8 = [
  '        if (error) return { supplierTransactions: [], error: this.normalizeError(error) };',
  '        return { supplierTransactions: data || [], error: null };',
  '      } catch (err) {',
  '        return { supplierTransactions: [], error: this.normalizeError(err) };',
  '      }',
  '    }',
  '',
  '    // Stage 8: Invoices & Invoice Items',
  '',
  '    async syncInvoiceToCloud(invPayload, cloudUuid, mappedCustomerId) {',
  '      if (!this.client) return { success: false, error: \'Supabase offline\' };',
  '      try {',
  '        const payload = {',
  '          invoice_number:  invPayload.id || invPayload.invoice_number || invPayload.invoiceNumber,',
  '          customer_name:   invPayload.customerName || \'Customer\',',
  '          customer_phone:  invPayload.customerPhone || null,',
  '          customer_gstin:  invPayload.customerGSTIN || null,',
  '          billing_address: invPayload.billingAddress || null,',
  '          date:            invPayload.date || new Date().toISOString().split(\'T\')[0],',
  '          due_date:        invPayload.dueDate || null,',
  '          status:          invPayload.status || \'Pending\',',
  '          tax_type:        invPayload.taxType || \'INTRA\',',
  '          subtotal:        Math.round((invPayload.subtotal || 0) * 100) / 100,',
  '          discount_total:  Math.round((invPayload.discountTotal || 0) * 100) / 100,',
  '          taxable_total:   Math.round((invPayload.taxableTotal || 0) * 100) / 100,',
  '          cgst_total:      Math.round((invPayload.cgstTotal || 0) * 100) / 100,',
  '          sgst_total:      Math.round((invPayload.sgstTotal || 0) * 100) / 100,',
  '          igst_total:      Math.round((invPayload.igstTotal || 0) * 100) / 100,',
  '          tax_total:       Math.round((invPayload.taxTotal || 0) * 100) / 100,',
  '          round_off:       Math.round((invPayload.roundOff || 0) * 100) / 100,',
  '          total:           Math.round((invPayload.total || 0) * 100) / 100,',
  '          note:            invPayload.note || null,',
  '          is_credit:       invPayload.isCredit || false,',
  '          is_deleted:      invPayload.isDeleted || false,',
  '          deleted_at:      invPayload.deletedAt || null,',
  '          deleted_by:      invPayload.deletedBy || null',
  '        };',
  '',
  '        if (invPayload.business_id) payload.business_id = invPayload.business_id;',
  '',
  '        if (mappedCustomerId && mappedCustomerId.length === 36 && mappedCustomerId.includes(\'-\')) {',
  '          payload.customer_id = mappedCustomerId;',
  '        } else if (invPayload.customerId && invPayload.customerId.length === 36 && invPayload.customerId.includes(\'-\')) {',
  '          payload.customer_id = invPayload.customerId;',
  '        } else {',
  '          payload.customer_id = null;',
  '        }',
  '',
  '        let response;',
  '        if (cloudUuid && cloudUuid.length === 36 && cloudUuid.includes(\'-\')) {',
  '          response = await this.client.from(\'invoices\').update(payload).eq(\'id\', cloudUuid).select().single();',
  '        } else {',
  '          response = await this.client.from(\'invoices\').insert(payload).select().single();',
  '        }',
  '',
  '        if (response.error) return { success: false, error: this.normalizeError(response.error) };',
  '        return { success: true, invoice: response.data };',
  '      } catch (err) {',
  '        return { success: false, error: this.normalizeError(err) };',
  '      }',
  '    }',
  '',
  '    async syncInvoiceItemsToCloud(cloudInvoiceId, businessId, items, productCloudMap) {',
  '      if (!this.client || !cloudInvoiceId) return { success: false, error: \'Offline or missing invoice UUID\' };',
  '      try {',
  '        const { error: delError } = await this.client.from(\'invoice_items\').delete().eq(\'invoice_id\', cloudInvoiceId);',
  '        if (delError && delError.code !== \'PGRST116\') {',
  '          console.warn(\'[Stage8] Invoice items delete warning:\', delError.message);',
  '        }',
  '        if (!items || items.length === 0) return { success: true, items: [] };',
  '',
  '        const rows = items.map((item, idx) => {',
  '          const row = {',
  '            business_id:  businessId,',
  '            invoice_id:   cloudInvoiceId,',
  '            item_name:    item.name || \'Item\',',
  '            hsn_code:     item.hsn || null,',
  '            unit:         item.unit || \'Pcs\',',
  '            quantity:     Math.max(0, parseFloat(item.qty) || 1),',
  '            rate:         Math.round((parseFloat(item.rate) || 0) * 100) / 100,',
  '            discount:     Math.round((parseFloat(item.discount) || 0) * 100) / 100,',
  '            taxable_val:  Math.round((parseFloat(item.taxableVal) || 0) * 100) / 100,',
  '            tax_rate:     Math.round((parseFloat(item.taxRate) || 18) * 100) / 100,',
  '            cgst:         Math.round((parseFloat(item.cgst) || 0) * 100) / 100,',
  '            sgst:         Math.round((parseFloat(item.sgst) || 0) * 100) / 100,',
  '            igst:         Math.round((parseFloat(item.igst) || 0) * 100) / 100,',
  '            total:        Math.round((parseFloat(item.total) || 0) * 100) / 100,',
  '            sort_order:   idx',
  '          };',
  '          if (item.productId && productCloudMap && productCloudMap[item.productId]) {',
  '            row.product_id = productCloudMap[item.productId];',
  '          } else if (item.productId && item.productId.length === 36 && item.productId.includes(\'-\')) {',
  '            row.product_id = item.productId;',
  '          }',
  '          return row;',
  '        });',
  '',
  '        const { data, error } = await this.client.from(\'invoice_items\').insert(rows).select();',
  '        if (error) return { success: false, error: this.normalizeError(error) };',
  '        return { success: true, items: data || [] };',
  '      } catch (err) {',
  '        return { success: false, error: this.normalizeError(err) };',
  '      }',
  '    }',
  '',
  '    async fetchInvoicesFromCloud(businessId) {',
  '      if (!this.client || !businessId) return { invoices: [], error: \'Offline mode or missing businessId\' };',
  '      try {',
  '        const { data, error } = await this.client',
  '          .from(\'invoices\')',
  '          .select(\'*\')',
  '          .eq(\'business_id\', businessId)',
  '          .order(\'date\', { ascending: false });',
  '        if (error) return { invoices: [], error: this.normalizeError(error) };',
  '        return { invoices: data || [], error: null };',
  '      } catch (err) {',
  '        return { invoices: [], error: this.normalizeError(err) };',
  '      }',
  '    }'
].join('\n');

const fixed = before + '\n' + stage8 + '\n' + after;
fs.writeFileSync('js/supabaseClient.js', fixed, 'utf8');
console.log('Written. Total lines:', fixed.split('\n').length);
